/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Tue Oct 25 2016 12:15:01 GMT+0000 (UTC)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
exports.ENV = {};

//# sourceMappingURL=env.js.map
